= Use Sealed Classes
:sectanchors:

In this hands-on exercise, you will utilize sealed classes to enhance the responses from your appointment service, making them more informative for its clients.

== Define sealed classes

Inside `com.example.dentalclinic.service`, create a new file `ScheduledResult.kt` that contains  sealed classes which represent responses from the appointment service:

[source,kotlin]
----
sealed interface ScheduleResult {
    data class Success(
        val appointmentId: String,
    ) : ScheduleResult

    data class DentalPractitionerUnavailable(
        val availableDentalPractitioners: List<DentalPractitioner>,
    ) : ScheduleResult

    data class TreatmentUnavailable(
        val availableTreatments: List<Treatment>,
    ) : ScheduleResult

    data class NotFound(val message: String) : ScheduleResult

    object TimeSlotUnavailable : ScheduleResult
}
----

== Modify Clinic object

* Introduce hygienists: `val hygienists = PersonManager<Hygienist>()`
* Rename parameter `dentistId` to `dentalPractitionerId` in `scheduleAppointment` function. You can use IntelliJ’s *Refactor | Rename…* functionality.
* Introduce an `isAvailable` function that will determine if a `DentalPractisioner` is available for treatment, for example a simulation which determines availability based on id:

[source,kotlin]
----
private fun isAvailable(person: DentalPractitioner): Boolean {
    return Character.getNumericValue(person.id.last()) % 2 == 0
}
----

== Modify the AppointmentRequest class

Open `AppontmentDTOs.kt` file and rename parameter `dentistId` to `dentalPractitionerId` in `AppointmentRequest` class:

[source,kotlin]
----
data class AppointmentRequest(
    val patientId: String,
    val dentalPractitionerId: String,
    val date: LocalDateTime,
    val treatmentType: String
)
----

== Modify the Appointment class

Update Appointment constructor to accept DentalPractitioner instead of Dentist:

[source,kotlin]
----
data class Appointment(
    val id: String,
    val patient: Patient,
    val dentalPractitioner: DentalPractitioner,
    // the rest of the constructor
)

----


== Revise the scheduleAppointment function in Clinic object

Enhance `scheduleAppointment` function with the `ScheduleResult` sealed interface to provide a schedule outcome.

* Replace validations for patient, treatment and dentist ids with validation that uses the new sealed classes:

[source,kotlin]
----
fun scheduleAppointment(
    // function parameters
): ScheduleResult {
    val patient =
        patients.getPersonById(patientId)
            ?: return ScheduleResult.NotFound(
                "Patient not found"
            )

    val treatment = treatments[treatmentId]
        ?: return ScheduleResult.TreatmentUnavailable(
            treatments.values.toList()
        )

    val dentalPractitioner: DentalPractitioner =
        findPersonAcrossManagers(
            dentalPractitionerId,
            dentists,
            hygienists
        ) ?: return ScheduleResult.NotFound(
            "Dental practitioner not found"
        )

    //The rest of the code
}
----

* Embed logic to check the dental practitioner’s availability and subsequently schedule the appointment if they are available. Based on conditions, return appropriate `ScheduleResult`:

[source,kotlin]
----
if (isAvailable(dentalPractitioner)) {
    val appointmentId = UUID.randomUUID().toString()
    appointments.add(
        Appointment(
            appointmentId,
            patient,
            dentalPractitioner,
            time,
            treatment,
        )
    )
    return ScheduleResult.Success(appointmentId)
} else {
    val availableDentists =
        dentists.findPersonsByCriteria {
            isAvailable(it)
        }
    val availableHygienists =
        hygienists.findPersonsByCriteria {
            isAvailable(it)
        }
    return ScheduleResult.DentalPractitionerUnavailable(
        availableDentists + availableHygienists
    )
}
----

== Integrate the scheduleAppointment function

Use `Clinic.scheduleAppointment` in the implementation of `AppointmentScheduler.schedule` function and handle result. Replace the current implementation of AppointmentScheduler.schedule with:

[source,kotlin]
----
val result = Clinic.scheduleAppointment(
    appointmentRequest.patientId,
    appointmentRequest.dentalPractitionerId,
    appointmentRequest.dateTime,
    appointmentRequest.treatmentId
)

return when (result) {
    is ScheduleResult.Success -> AppointmentResponse(
        id = result.appointmentId,
        message = successMessage(),
    )

    is ScheduleResult.TimeSlotUnavailable -> AppointmentResponse(
        message = "Time slot unavailable!",
    )

    is ScheduleResult.TreatmentUnavailable -> {
        val ids =
            result.availableTreatments.map { it.id }
        val msg =
            "Treatment unavailable! Available treatments: $ids"
        AppointmentResponse(message = msg)
    }

    is ScheduleResult.DentalPractitionerUnavailable -> {
        val ids =
            result.availableDentalPractitioners.map { it.id }
        val msg =
            "Practitioner unavailable! Who is available: $ids"
        AppointmentResponse(message = msg)
    }

    is ScheduleResult.NotFound -> AppointmentResponse(
        message = result.message,
    )
}
----


== Update Controller to return error response code
Let's return HTTP status code 422 when appointment could not be made. Update `AppointmentController.scheduleAppointment` function to return OK only when appointment is made, and `HttpStatus.UNPROCESSABLE_ENTITY` response code when appointment could not be made:

[source,kotlin]
----
 return if (appointmentResult.id != null)
            ResponseEntity.ok(
                appointmentResult
            )
        else ResponseEntity.status(HttpStatus.UNPROCESSABLE_ENTITY)
            .body(appointmentResult)

----

== Populate data

Bootstrap your clinic with preliminary data. In Spring, one common way to populate data on startup is using an event listener. Let us do this with the `ContextRefreshedEvent`. This event is fired when the application context is initialized or refreshed. Define a `DataLoader` class in a new package `com.example.dentalclinic.bootstrap`:

[source,kotlin]
----
@Component
class DataLoader {

    @EventListener(ContextRefreshedEvent::class)
    fun populateInitialData() {
        val patient = Patient("P001", "John Doe")
        Clinic.patients.addPerson(patient)
        val hygienist = Hygienist("DP001", "Ms. Claire")
        Clinic.hygienists.addPerson(hygienist)
        val dentist = Dentist("DP002", "Dr. Smith")
        Clinic.dentists.addPerson(dentist)
        Clinic.addTreatment(Treatment.teethCleaning())
    }
}
----

== Execution

Run `DentalClinicApplication.kt`. Use Swagger at http://localhost:8080/swagger-ui.html to experiment with appointments endpoint. E.g. successful request:

[source,json]
----
{
  "patientId": "P001",
  "dentalPractitionerId": "DP002",
  "dateTime": "2023-08-21T09:32:23.803Z",
  "treatmentId": "T001"
}
----

Attempt with a non-existent patient or practitioner to trigger a 422 response co,de or with an existing dental practitioner that is currently unavailable for appointment, like `dentalPractitionerId: "DP001"`to get a list of available dental practitioners:

[source,json]
----
{
  "patientId": "P001",
  "dentalPractitionerId": "DP001",
  "dateTime": "2023-08-21T09:32:23.803Z",
  "treatmentId": "T001"
}
----


➡️ link:./12-value-classes.adoc[12. Value Classes]

⬅️ link:./10-generics.adoc[10. Generics]
